In [1]:
import matplotlib.pyplot as plt
%matplotlib inline
# %matplotlib qt
%load_ext autoreload
%autoreload 2
import numpy as np
import time
import random
def print_np(x):
    print ("Type is %s" % (type(x)))
    print ("Shape is %s" % (x.shape,))
#     print ("Values are: \n%s" % (x))
from scipy.interpolate import interp1d

In [2]:
import sys
# sys.path.append('../')
sys.path.append('../')
sys.path.append('../model')
sys.path.append('../cost')
sys.path.append('../constraints')
sys.path.append('../utils')
from scipy.integrate import solve_ivp
from HypersonicEntry3DofPolar import Entry3dofSpherical

## Skye

In [3]:
tf = 1.04*1600
N = 30
delT = tf/N
sigma_init = np.linspace(0,np.deg2rad(-10),N+1)
ix = 6
iu = 1

In [4]:
my_model = Entry3dofSpherical("hi",ix,iu,linearization="analytic")


In [5]:
Ts_init = tf / my_model.nt
dts_init = delT/my_model.nt
ts_init = np.linspace(0,Ts_init,N+1)

In [6]:
u_t = interp1d(ts_init,sigma_init)

In [7]:
h0 = 100*1e3
r0_s     = (h0+my_model.re)/my_model.nd;  
theta0_s = 0
phi0_s   = 0
v0_s     = 7450/my_model.nv
gamma0   = np.deg2rad(-0.5)
psi0     = np.deg2rad(90)

x0_s = [r0_s,theta0_s,phi0_s,v0_s,gamma0,psi0]
print(x0_s)

[1.0156961230576047, 0, 0, 0.9423624367981697, -0.008726646259971648, 1.5707963267948966]


In [8]:
def dfdt(t,x,t0,u0) :
    u_t = interp1d(t0,u0)
    u = u_t(t)
    return np.squeeze(my_model.forward(x,u))

In [9]:
sol = solve_ivp(dfdt,(ts_init[0],ts_init[-1]),x0_s,args=(ts_init,sigma_init),t_eval=ts_init,rtol=1e-12,atol=1e-12)


In [10]:
sol.y[:,-1]

array([ 1.00476425,  1.28343912,  0.03778173,  0.12249751, -0.08225446,
        1.15150802])

In [11]:
sigma_init

array([ 0.        , -0.00581776, -0.01163553, -0.01745329, -0.02327106,
       -0.02908882, -0.03490659, -0.04072435, -0.04654211, -0.05235988,
       -0.05817764, -0.06399541, -0.06981317, -0.07563093, -0.0814487 ,
       -0.08726646, -0.09308423, -0.09890199, -0.10471976, -0.11053752,
       -0.11635528, -0.12217305, -0.12799081, -0.13380858, -0.13962634,
       -0.1454441 , -0.15126187, -0.15707963, -0.1628974 , -0.16871516,
       -0.17453293])

In [12]:
x = sol.y.T
u = np.expand_dims(sigma_init,1)
print_np(x)
print_np(u)

Type is <class 'numpy.ndarray'>
Shape is (31, 6)
Type is <class 'numpy.ndarray'>
Shape is (31, 1)


In [15]:
x[-1,:]

array([ 1.00476425,  1.28343912,  0.03778173,  0.12249751, -0.08225446,
        1.15150802])

In [14]:
A,Bm,Bp,s,z,x_prop_n = my_model.diff_discrete_foh(x[0:N,:],u,dts_init,Ts_init)

In [16]:
print_np(A)

Type is <class 'numpy.ndarray'>
Shape is (30, 6, 6)


## Behcet

In [ ]:
h0 = 100*1e3
r0_s     = (h0+my_model.re)/my_model.nd;  
theta0_s = 0
phi0_s   = 0
v0_s     = 7450/my_model.nv
gamma0   = np.deg2rad(-0.5)
psi0     = 0

x0_s = [r0_s,theta0_s,phi0_s,v0_s,gamma0,psi0]
print(x0_s)

In [ ]:
def dfdt(t,x,t0,u0) :
    u_t = interp1d(t0,u0)
    u = u_t(t)
    return np.squeeze(my_model.forward(x,u))

In [ ]:
sol = solve_ivp(dfdt,(ts_init[0],ts_init[-1]),x0_s,
    args=([ts_init[0],ts_init[-1]],[sigma_init[0],sigma_init[1]]),
    t_eval=ts_init,rtol=1e-12,atol=1e-12)


In [ ]:
x = sol.y.T
u = np.expand_dims(sigma_init,1)

In [ ]:
ts_init

In [ ]:
Ts_init

In [ ]:
dts_init * np.ones(N)

In [ ]:
A,Bm,Bp,s,z,x_prop_n = my_model.diff_discrete_foh(x[0:N,:],u,dts_init,Ts_init)
# A,Bm,Bp,s,z,x_prop_n = my_model.diff_discrete_foh_var_vectorized(x[0:N,:],u,dts_init * np.ones(N))

In [ ]:
A[-1,:,:]

In [ ]:
x_prop_n[-1]

In [ ]:
x[1]

In [ ]:
u[1]

In [ ]:
A,B = my_model.diff_numeric_central(x[1],u[1])

In [ ]:
A[:,:,3]

In [ ]:
x[24]

In [ ]:
u[24]

In [ ]:
A,B = my_model.diff(x[24],u[24])

In [ ]:
A